const MostWatchedMovies = [
  {
    id: 1,
    title: "Animal : Park",
    year: 2023,
    type: "Action / Thriller",
    price: 170,
    category: "Most Watched",
    image: "https://miro.medium.com/v2/resize:fit:1400/1*FovLrh7If7fq1r1gh5oD1A.jpeg",
    desc: "A gripping action-thriller that delves into the primal instincts of a man entangled in a web of violence, loyalty, and survival. As danger closes in, he must confront both external enemies and his own inner demons.",
    director: "Sandeep Reddy Vanga",
    writers: ["Saurabh Gupta", "Sandeep Reddy Vanga"],
    stars: ["Ranbir Kapoor", "Parineeti Chopra", "Anil Kapoor"]
  },
  {
    id: 2,
    title: "Kanchana 2",
    year: 2015,
    type: "Thriller / Horror",
    price: 210,
    category: "Most Watched",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNkHitirKSn0DAgjSQQ8XlMJqRGy3qdav5Tg&s",
    desc: "A terrifying blend of horror and comedy where a ghost seeks revenge through an unlikely host. The film explores themes of fear, redemption, and spiritual justice with spine-chilling sequences.",
    director: "Raghava Lawrence",
    writers: ["Raghava Lawrence"],
    stars: ["Raghava Lawrence", "Taapsee Pannu", "Nithya Menen"]
  },
   {
    id: 3,
    title: "Bahubali 2",
    year: 2017,
    type: "Action",
    price: 180,
    category: "Most Watched",
    image: "https://m.media-amazon.com/images/M/MV5BYjAwZWE2NmUtYjFjYy00Y2EyLTg4OTgtNmQ0NTQyY2M0NjE1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "In ancient India, a couple rescues a baby who will grow up to become the man who will change the course of an old war.",
    director: "S.s Rajamouli",
    writers: ["Sekhar Kammula"],
    stars: "Prabhas (prabhas raju uppala, Rana Daggubati, Anushka Shetty, Tamannaah Bhatia"
  },
  {
    id: 4,
    title: "Phir Hera Pheri",
    year: 2006,
    type: "Comedy",
    price: 150,
    category: "Most Watched",
    image: "https://m.media-amazon.com/images/M/MV5BMTNkZTExMWYtMGZjMy00NGUwLWJmMWEtOThjYmZjY2Q0N2M5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "The iconic trio is back with their hilarious antics and endless chaos. A wild ride filled with misunderstandings, scams, and laughter as the characters chase a fortune that keeps slipping away.",
    director: "Neeraj Vora",
    writers: ["Neeraj Vora", "J. D. Chakravarthy"],
    stars: ["Akshay Kumar", "Sunil Shetty", "Paresh Rawal"]
  },
  {
    id: 5,
    title: "Horror Story",
    year: 2017,
    type: "Horror",
    price: 180,
    category: "Most Watched",
    image: "https://m.media-amazon.com/images/M/MV5BOGQ2NmMyZDItOTEwNy00YjVkLTllYTUtMTQyOWI5YjhjNjcxXkEyXkFqcGc@._V1_.jpg",
    desc: "Seven friends spend a night in a haunted hotel and face paranormal horrors beyond imagination. The movie delivers a chilling narrative with jump scares, suspense, and an eerie atmosphere.",
    director: "Ayush Raina",
    writers: ["Vikram Bhatt", "Mohan Azad"],
    stars: ["Karan Kundrra", "Ravish Desai", "Nishant Malkani"]
  },
  {
    id: 6,
    title: "Fidaa",
    year: 2018,
    type: "Love / Drama",
    price: 140,
    category: "Most Watched",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmdRf5hNQJfS1JPFWD4vAaptVSYEUE6Pe_tA&s",
    desc: "A tender love story between a spirited village girl and an NRI that explores cultural differences, emotional conflicts, and heartfelt romance. A tale of love that transcends distances.",
    director: "Sekhar Kammula",
    writers: ["Sekhar Kammula"],
    stars: ["Varun Tej", "Sai Pallavi"]
  },
  {
    id: 7,
    title: "Kanchana",
    year: 2011,
    type: "Horror",
    price: 200,
    category: "Most Watched",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvGgGXYAuz23ayR-QedY0JsXmn8ajUVm4DPA&s",
    desc: "A horror-comedy that follows a man possessed by a vengeful spirit. The movie blends slapstick humor with genuine scares and highlights social issues in a unique way.",
    director: "Raghava Lawrence",
    writers: ["Raghava Lawrence"],
    stars: ["Raghava Lawrence", "Sarathkumar", "Lakshmi Rai"]
  },
  {
    id: 8,
    title: "Bajrangi Bhaijaan",
    year: 2015,
    type: "Drama",
    price: 150,
    category: "Most Watched",
    image: "https://m.media-amazon.com/images/M/MV5BYzVjMjZiNGUtZjZiNy00Yzg4LWEzYzYtMmI1NDg5NWNiNjUwXkEyXkFqcGc@._V1_.jpg",
    desc: "A moving story of a kind-hearted man who helps a mute girl from Pakistan reunite with her family. A journey that transcends borders and beliefs, filled with emotion and humanity.",
    director: "Kabir Khan",
    writers: ["Vijayendra Prasad", "Kabir Khan"],
    stars: ["Salman Khan", "Harshaali Malhotra", "Nawazuddin Siddiqui"]
  },
  {
    id: 9,
    title: "Welcome",
    year: 2009,
    type: "Comedy",
    price: 100,
    category: "Most Watched",
    image: "https://upload.wikimedia.org/wikipedia/en/f/f4/Welcome_poster_2007.jpg",
    desc: "A laugh-out-loud comedy about a man who falls in love with a gangster's sister, leading to a series of hilarious and chaotic events. A Bollywood classic with a stellar ensemble cast.",
    director: "Anees Bazmee",
    writers: ["Anees Bazmee", "Rajiv Kaul"],
    stars: ["Akshay Kumar", "Katrina Kaif", "Anil Kapoor", "Nana Patekar"]
  },
  {
    id: 10,
    title: "Dhamaal",
    year: 2007,
    type: "Comedy",
    price: 100,
    category: "Most Watched",
    image: "https://upload.wikimedia.org/wikipedia/en/6/60/Dhamaal_2007.jpg",
    desc: "Four jobless friends stumble upon a hidden treasure map that leads to a hilarious treasure hunt filled with absurd situations, quirky characters, and slapstick humor.",
    director: "Indra Kumar",
    writers: ["Paritosh Painter", "Indra Kumar"],
    stars: ["Riteish Deshmukh", "Arshad Warsi", "Javed Jaffrey", "Sanjay Dutt"]
  },
  {
    id: 11,
    title: "3 Idiots",
    year: 2009,
    type: "Comedy",
    price: 120,
    category: "Most Watched",
    image: "https://m.media-amazon.com/images/M/MV5BNzc4ZWQ3NmYtODE0Ny00YTQ4LTlkZWItNTBkMGQ0MmUwMmJlXkEyXkFqcGc@._V1_.jpg",
    desc: "A thought-provoking comedy that questions the Indian education system while following three friends through college life, self-discovery, and friendship. Inspiring and unforgettable.",
    director: "Rajkumar Hirani",
    writers: ["Abhijat Joshi"]
  },
  {
    id: 12,
    title: "3 BHK",
    year: 2024,
    type: "Family",
    price: 130,
    category: "Most Watched",
    image: "https://m.media-amazon.com/images/M/MV5BZTU0ODU1MjgtZmY0OC00Njc2LWFhY2YtZWU2MDk1YThkMzkxXkEyXkFqcGc@._V1_.jpg",
    desc: "A heartfelt story of a middle-class family moving into a dream home, only to discover that true comfort lies in emotional bonds rather than material spaces. A touching portrayal of relationships and aspirations.",
    director: "Vikram Mehra",
    writers: ["Anjali Nair", "Vikram Mehra"],
    stars: ["Neena Gupta", "Rajkummar Rao", "Amrita Subhash"]
  },
    ]
    export default MostWatchedMovies